### ISSUE TITLE
General cleanup of ShopifyProduct and others

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/shopify#12]
This issue is here just to allow me to provide a PR that fixes several issues:

-  Issues with the entity class ShopifyProduct for the shopify_product entity type
-  Syntax sssues with taxonomy term code for collections,
- Issues with Shopify Rest API call to get paginated results (apparently b/c of using old API syntax - this is not solved in the PR - rather it's commented out to allow for testing)  
- Etc.

I've added comments to some of the changes in the PR. Please test.

**Comment by argiepiano** [comment]
PR #13. Please test.

**Comment by laryn** [comment]
@argiepiano I've merged your PR as a big step forward and will continue to clean things up (and try to find solutions to the items you flagged). Thanks so much for pitching in!
