### ISSUE TITLE
Entity Plus tweaks needed

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/shopify#22]
> Theme hook "entity_property" not found.

This should likely be `entity_plus_property`.

**Comment by laryn** [comment]
I think due to this commit I'm now seeing this:

> Argument 1 passed to entity_plus_property_default_render_value_by_type() must be an instance of EntityMetadataWrapper, null given, called in /app/web/modules/entity_plus/theme/entity_plus.theme.inc on line 100

**Comment by laryn** [comment]
I'm also seeing in class `ShopifyProductMetadataController` a number of references to `entity_property_verbatim_date_set` and `entity_property_verbatim_date_get` that likely need to be addressed.

**Comment by argiepiano** [comment]
PR submitted.

Important: Use the dev version of Entity Plus (current E+ version is 1.0.15)
