### ISSUE TITLE
Add a call to setUp() in __construct method of ShopifyProduct class

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/shopify#23]
Originally this call was included in D7 Entity API `Entity` class, but it's not in Backdrop's core `Entity` class.

**Comment by laryn** [comment]
- Notice: Undefined index: entity keys in ShopifyProduct->setUp() (line 346 of /app/web/modules/shopify/includes/shopify.entity.inc).
 - Notice: Trying to access array offset on value of type null in ShopifyProduct->setUp() (line 346 of /app/web/modules/shopify/includes/shopify.entity.inc).
