### ISSUE TITLE
Rename `theme_entity_property__shopify_product__price` and `...body_html`

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/shopify#28]
> The functions `theme_entity_property__shopify_product__price` and `theme_entity_property__shopify_product__body_html` will need to be renamed by adding `_plus_`. Those functions are in `shopify.module`.

**Comment by argiepiano** [comment]
In addition to renaming the functions, the theme declaration in `shopify_theme()` needs to be changed as well.

**Comment by argiepiano** [comment]
PR ready.

**Comment by argiepiano** [comment]
A new problem appears now that the preprocess function is called - `Notice: Undefined index: title_attributes in theme_entity_plus_property__shopify_product__price() (line 1660 `

**Comment by argiepiano** [comment]
That second issue is now fixed. Backdrop removed the theme `process` layer, resulting in array of attributes being passed to theme functions (instead of a string). Thus the need to use `backdrop_attributes()` to convert the array into html attributes.
